name: haumonsters
description: HAU Pokemon Monster App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.1
  audioplayers: ^6.0.0
  torch_light: ^1.1.0
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/monster_alarm.wav
